workflows:
  android-workflow:
    name: Android Workflow (DEV)
    # instance_type: mac_mini_m2 # <-- Removed as per sggestion from Codemagic team, since instance allocated is Special M4 Pro
    max_build_duration: 120
    environment:
      xcode: 16.2
      android_signing:
        - CodeMagic Debug Key
      groups:
        - google_play # <-- (Includes GCLOUD_SERVICE_ACCOUNT_CREDENTIALS)
      vars:
        PACKAGE_NAME: "io.codemagic.flutteryaml" # <-- Put your package name here
        GOOGLE_PLAY_TRACK: "alpha"
      flutter: stable
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Build AAB with flutter
        script: |
          flutter build appbundle --release
      - name: Build APK with flutter
        script: |
          flutter build apk --release
      - name: Flutter unit tests
        script: |
          flutter test
        ignore_failure: true
      # - name: Build AAB with Flutter
      #   script: |
      #     BUILD_NUMBER=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME" --tracks="$GOOGLE_PLAY_TRACK") + 1))
      #     flutter build appbundle --release \
      #       --build-name=1.0.$BUILD_NUMBER \
      #       --build-number=$BUILD_NUMBER
    artifacts:
      # - build/**/outputs/*
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - dicky.hk.chu@prudential.com.hk
        notify:
          success: true
          failure: false
      # google_play:
      #   credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
      #   track: $GOOGLE_PLAY_TRACK
      #   submit_as_draft: true

  ios-workflow:
    name: iOS Workflow (DEV)
    # instance_type: mac_mini_m2 # <-- Removed as per sggestion from Codemagic team, since instance allocated is Special M4 Pro
    max_build_duration: 120
    # integrations:
    #   app_store_connect: codemagic
    environment:
      ios_signing:
        distribution_type: development # ad_hoc | development | enterprise
        bundle_identifier: com.prudential.pruservices.dev
      vars:
        APP_ID: 2LQYQD27P7 # <-- Put your APP ID here
      flutter: stable
      xcode: 16.2 # <-- set to specific version e.g. 14.3, 15.0 to avoid unexpected updates.
      cocoapods: default
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter unit tests
        script: |
          flutter test
        ignore_failure: true
      - name: Flutter build ipa
        script: |
          flutter build ipa --export-options-plist=/Users/builder/export_options.plist
      # - name: Flutter build ipa and automatic versioning
      #   script: |
      #     # See the following link about getting the latest App Store or TestFlight version - https://docs.codemagic.io/knowledge-codemagic/build-versioning/#app-store-or-testflight-latest-build-number
      #     flutter build ipa --release \
      #       --build-name=1.0.0 \
      #       --build-number=$(($(app-store-connect get-latest-testflight-build-number --platform=IOS "$APP_ID") + 1)) \
      #       --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      # See the following link for details about email publishing - https://docs.codemagic.io/publishing-yaml/distribution/#email
      email:
        recipients:
          - dicky.hk.chu@prudential.com.hk
        notify:
          success: true # To receive a notification when a build succeeds
          failure: false # To not receive a notification when a build fails
      # slack:
      #   # See the following link about how to connect your Slack account - https://docs.codemagic.io/publishing-yaml/distribution/#slack
      #   channel: "#builds"
      #   notify_on_build_start: true # To receive a notification when a build starts
      #   notify:
      #     success: true # To receive a notification when a build succeeds
      #     failure: false # To not receive a notification when a build fails
      # app_store_connect:
      #   auth: integration

      #   # Configuration related to TestFlight (optional)
      #   # Note: This action is performed during post-processing.
      #   submit_to_testflight: true
      #   beta_groups: # Specify the names of beta tester groups that will get access to the build once it has passed beta review.
      #     - group name 1
      #     - group name 2

      #   # Configuration related to App Store (optional)
      #   # Note: This action is performed during post-processing.
      #   submit_to_app_store: false

  iOS-Android-workflow:
    name: iOS & Android Workflow (DEV)
    # instance_type: mac_mini_m2 # <-- Removed as per sggestion from Codemagic team, since instance allocated is Special M4 Pro
    max_build_duration: 120
    integrations:
      app_store_connect: Code Magic API Key
    environment:
      ios_signing:
        distribution_type: development # ad_hoc | development | enterprise
        bundle_identifier: com.prudential.pruservices.dev
      android_signing:
        - CodeMagic Debug Key
      vars:
        APP_ID: 2LQYQD27P7 # iOS Team ID
        ANDROID_PACKAGE_NAME: "com.prudential.pruservices.dev"
      flutter: stable
      xcode: 16.2 # <-- set to specific version e.g. 14.3, 15.0 to avoid unexpected updates.
      cocoapods: default
    triggering:
      events:
        - push # <-- Trigger on push to the repository
        - pull_request
      branch_patterns:
        - pattern: "master"
          include: true
          source: false
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter unit tests
        script: |
          flutter test
        ignore_failure: true
      - name: Flutter build ipa
        script: |
          flutter build ipa --export-options-plist=/Users/builder/export_options.plist --build-name=1.0.$PROJECT_BUILD_NUMBER --build-number=$PROJECT_BUILD_NUMBER
      - name: Android - Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Android - Build AAB with flutter
        script: |
          flutter build appbundle --release --build-name=1.0.$PROJECT_BUILD_NUMBER --build-number=$PROJECT_BUILD_NUMBER
      - name: Android - Build APK with flutter # <-- --build-name=1.0.1 --build-number=2
        script: |
          flutter build apk --release --build-name=1.0.$PROJECT_BUILD_NUMBER --build-number=$PROJECT_BUILD_NUMBER
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
      - build/**/outputs/**/*.aab
      # - build/**/outputs/**/*.apk
      - build/**/outputs/flutter-apk/*.apk
      - build/**/outputs/**/mapping.txt
    publishing:
      # See the following link for details about email publishing - https://docs.codemagic.io/publishing-yaml/distribution/#email
      email:
        recipients:
          - dicky.hk.chu@prudential.com.hk
          - xiongbo.cen@prudential.com.cn
          - peter.mekhaeil@prudential.com.sg
        notify:
          success: true # To receive a notification when a build succeeds
          failure: false # To not receive a notification when a build fails
      slack:
        # See the following link about how to connect your Slack account - https://docs.codemagic.io/publishing-yaml/distribution/#slack
        channel: "#gtp-gbl-codemagic"
        notify_on_build_start: true # To receive a notification when a build starts
        notify:
          success: true # To receive a notification when a build succeeds
          failure: false # To not receive a notification when a build fails
      app_store_connect:
        auth: integration

        # Configuration related to TestFlight (optional)
        # Note: This action is performed during post-processing.
        submit_to_testflight: false # Internal Tester only
        beta_groups: # Specify the names of beta tester groups that will get access to the build once it has passed beta review.
          - UAT Testers

        # Configuration related to App Store (optional)
        # Note: This action is performed during post-processing.
        submit_to_app_store: false

  # web-workflow:
  #   name: Web app workflow
  #   max_build_duration: 10
  #   environment:
  #     flutter: stable
  #   scripts:
  #     - name: Get Flutter packages
  #       script: |
  #         flutter packages pub get
  #     - name: Flutter analyze
  #       script: |
  #         flutter analyze
  #     - name: Flutter unit tests
  #       script: |
  #         flutter test
  #     - name: Flutter build webapp
  #       script: |
  #         flutter build web --release
  #         cd build/web
  #         7z a -r ../web.zip ./*
  #   artifacts:
  #     - build/web.zip
  #     - flutter_drive.log
  #   publishing:
  #     email:
  #       recipients:
  #         - user_1@example.com
